CREATE TABLE [dbo].[CAUHOI]
(
	[MaCH] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [Cauhoi] NVARCHAR(MAX) NULL, 
    [A] NVARCHAR(MAX) NULL, 
    [B] NVARCHAR(MAX) NULL, 
    [C] NVARCHAR(MAX) NULL, 
    [D] NVARCHAR(MAX) NULL, 
    [Dapan] NVARCHAR(50) NULL
)
